
export const tarotCards = [
  // Major Arcana
  { name: "The Fool", meaning: "New beginnings, spontaneity, freedom" },
  { name: "The Magician", meaning: "Power, skill, manifestation" },
  { name: "The High Priestess", meaning: "Intuition, mystery, subconscious" },
  { name: "The Empress", meaning: "Abundance, nurturing, fertility" },
  { name: "The Emperor", meaning: "Authority, structure, control" },
  { name: "The Hierophant", meaning: "Tradition, religion, conformity" },
  { name: "The Lovers", meaning: "Love, relationships, choices" },
  { name: "The Chariot", meaning: "Determination, willpower, victory" },
  { name: "Strength", meaning: "Courage, patience, inner strength" },
  { name: "The Hermit", meaning: "Introspection, solitude, guidance" },
  { name: "Wheel of Fortune", meaning: "Change, cycles, fate" },
  { name: "Justice", meaning: "Fairness, truth, law" },
  { name: "The Hanged Man", meaning: "Sacrifice, surrender, new perspective" },
  { name: "Death", meaning: "Transformation, endings, new beginnings" },
  { name: "Temperance", meaning: "Balance, moderation, purpose" },
  { name: "The Devil", meaning: "Bondage, addiction, materialism" },
  { name: "The Tower", meaning: "Sudden change, upheaval, revelation" },
  { name: "The Star", meaning: "Hope, faith, rejuvenation" },
  { name: "The Moon", meaning: "Illusion, fear, anxiety" },
  { name: "The Sun", meaning: "Joy, success, vitality" },
  { name: "Judgement", meaning: "Rebirth, inner calling, absolution" },
  { name: "The World", meaning: "Completion, accomplishment, travel" },
  
  //Minor Arcana
  // Wands
  { name: "Ace of Wands", meaning: "Inspiration, new opportunities, growth" },
  { name: "Two of Wands", meaning: "Planning, decisions, progress" },
  { name: "Three of Wands", meaning: "Expansion, foresight, leadership" },
  { name: "Four of Wands", meaning: "Celebration, harmony, home" },
  { name: "Five of Wands", meaning: "Conflict, competition, challenges" },
  { name: "Six of Wands", meaning: "Victory, recognition, success" },
  { name: "Seven of Wands", meaning: "Defense, perseverance, standing your ground" },
  { name: "Eight of Wands", meaning: "Movement, speed, swift action" },
  { name: "Nine of Wands", meaning: "Resilience, courage, persistence" },
  { name: "Ten of Wands", meaning: "Burden, responsibility, hard work" },
  { name: "Page of Wands", meaning: "Exploration, enthusiasm, discovery" },
  { name: "Knight of Wands", meaning: "Energy, passion, adventure" },
  { name: "Queen of Wands", meaning: "Confidence, independence, warmth" },
  { name: "King of Wands", meaning: "Leadership, vision, entrepreneurship" },

  // Cups
  { name: "Ace of Cups", meaning: "Emotional beginnings, love, compassion" },
  { name: "Two of Cups", meaning: "Partnership, unity, connection" },
  { name: "Three of Cups", meaning: "Friendship, celebration, community" },
  { name: "Four of Cups", meaning: "Contemplation, apathy, reevaluation" },
  { name: "Five of Cups", meaning: "Loss, regret, disappointment" },
  { name: "Six of Cups", meaning: "Nostalgia, memories, reunion" },
  { name: "Seven of Cups", meaning: "Choices, illusion, wishful thinking" },
  { name: "Eight of Cups", meaning: "Withdrawal, moving on, searching" },
  { name: "Nine of Cups", meaning: "Contentment, satisfaction, gratitude" },
  { name: "Ten of Cups", meaning: "Happiness, fulfillment, family" },
  { name: "Page of Cups", meaning: "Creativity, curiosity, possibility" },
  { name: "Knight of Cups", meaning: "Romance, charm, imagination" },
  { name: "Queen of Cups", meaning: "Compassion, calm, intuition" },
  { name: "King of Cups", meaning: "Emotional balance, diplomacy, wisdom" },

  // Swords
  { name: "Ace of Swords", meaning: "Clarity, truth, new ideas" },
  { name: "Two of Swords", meaning: "Indecision, choices, stalemate" },
  { name: "Three of Swords", meaning: "Heartbreak, sorrow, grief" },
  { name: "Four of Swords", meaning: "Rest, recovery, contemplation" },
  { name: "Five of Swords", meaning: "Conflict, tension, betrayal" },
  { name: "Six of Swords", meaning: "Transition, healing, moving forward" },
  { name: "Seven of Swords", meaning: "Deception, strategy, stealth" },
  { name: "Eight of Swords", meaning: "Restriction, fear, feeling trapped" },
  { name: "Nine of Swords", meaning: "Anxiety, worry, nightmares" },
  { name: "Ten of Swords", meaning: "Endings, loss, betrayal" },
  { name: "Page of Swords", meaning: "Curiosity, vigilance, communication" },
  { name: "Knight of Swords", meaning: "Action, speed, ambition" },
  { name: "Queen of Swords", meaning: "Intelligence, independence, perception" },
  { name: "King of Swords", meaning: "Authority, truth, intellectual power" },

  // Pentacles
  { name: "Ace of Pentacles", meaning: "Opportunity, prosperity, new beginnings" },
  { name: "Two of Pentacles", meaning: "Balance, adaptability, time management" },
  { name: "Three of Pentacles", meaning: "Teamwork, collaboration, skill" },
  { name: "Four of Pentacles", meaning: "Control, security, conservatism" },
  { name: "Five of Pentacles", meaning: "Hardship, poverty, isolation" },
  { name: "Six of Pentacles", meaning: "Generosity, charity, sharing" },
  { name: "Seven of Pentacles", meaning: "Assessment, patience, investment" },
  { name: "Eight of Pentacles", meaning: "Apprenticeship, mastery, diligence" },
  { name: "Nine of Pentacles", meaning: "Abundance, luxury, self-sufficiency" },
  { name: "Ten of Pentacles", meaning: "Legacy, inheritance, family" },
  { name: "Page of Pentacles", meaning: "Manifestation, financial opportunity, study" },
  { name: "Knight of Pentacles", meaning: "Hard work, responsibility, routine" },
  { name: "Queen of Pentacles", meaning: "Practicality, creature comforts, security" },
  { name: "King of Pentacles", meaning: "Wealth, business, leadership" },
]

